import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import basicSsl from '@vitejs/plugin-basic-ssl'
import path from 'path'

const isDev = process.env.NODE_ENV !== 'production';

export default defineConfig({
  plugins: [react(), ...(isDev ? [basicSsl()] : [])],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    open: true,
    https: {
      key: undefined,
      cert: undefined,
      // This will use the self-signed certificate generated by @vitejs/plugin-basic-ssl
    },
    host: '0.0.0.0',
    strictPort: true,
    hmr: {
      protocol: 'wss',
      host: 'snugging-discontentedly-daxton.ngrok-free.dev'
    },
    allowedHosts: [
      'snugging-discontentedly-daxton.ngrok-free.dev',
      '.ngrok-free.dev',
      'localhost'
    ]
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
})
